import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "@/stylesheets/commonClasses.css";
 import "@/stylesheets/antdOverride.css";
 import "@/stylesheets/layout.css";
 import "@/stylesheets/loader.css";
import LayoutProvider from "@/components/LayoutProvider"
import ReduxProvider from "@/components/ReduxProvider";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
       <LayoutProvider>
          {children}
        </LayoutProvider>  
        </ReduxProvider>      
      </body>
    </html>
  )
}
